export {default as H1} from './H1.svelte'
export {default as H2} from './H2.svelte'
export {default as H3} from './H3.svelte'
export {default as H4} from './H4.svelte'
export {default as H5} from './H5.svelte'
export {default as H6} from './H6.svelte'
export {default as Heading} from './Heading.svelte'